import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  courseSidebar: [
    {
      type: 'category',
      label: 'Beginner',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'beginner'}],
    },
    {
      type: 'category',
      label: 'Intermediate',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'intermediate'}],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'advanced'}],
    },
  ],
};

export default sidebars;
