# Dissecting variables
v = input('Type something: ')
print('The primitive type is: ', type(v))
print('Only spaces? ', v.isspace())
print('Is a number? ', v.isnumeric())
print('Is alphabetic?', v.isalpha())
print('Is alphanumeric? ', v.isalnum())
print('Is uppercase? ', v.isupper())
print('Is lowercase?', v.islower())
print('Is capitalized?', v.istitle())
